### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException:“Table 'testdb.keymaster' doesn't exist”

### ISSUE THREAD

**Issue by objectboy2016** [ericdc1/Dapper.SimpleCRUD#163]
MySql.Data.MySqlClient.MySqlException
  HResult=0x80004005
  Message=Table 'testdb.keymaster' doesn't exist
  Source=MySql.Data
  StackTrace:
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1064
   at Dapper.SqlMapper.<QueryImpl>d__138`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1081
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723
   at Dapper.SqlMapper.Query(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 650
   at Dapper.SimpleCRUD.Insert[TKey,TEntity](IDbConnection connection, TEntity entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in C:\Users\Administrator\Desktop\Dapper.SimpleCRUD-master\Dapper.SimpleCRUD\SimpleCRUD.cs:line 378
   at Dapper.SimpleCRUD.Insert[TEntity](IDbConnection connection, TEntity entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in C:\Users\Administrator\Desktop\Dapper.SimpleCRUD-master\Dapper.SimpleCRUD\SimpleCRUD.cs:line 307
   at Dapper.SimpleCRUDTests.Tests.TestFilteredGetListWithMultipleKeys() in C:\Users\Administrator\Desktop\Dapper.SimpleCRUD-master\Dapper.SimpleCRUDTests\Tests.cs:line 296

**Comment by ericdc1** [comment]
I see the issue. I didn't add the sql statements for mysql for a few new tests. 

https://github.com/ericdc1/Dapper.SimpleCRUD/commit/2ed40042f40642321710d1904cc17b5d6df64579
