### ISSUE TITLE
I got exceptions when I use Insert method for MySQL

### ISSUE THREAD

**Issue by game-libgdx-unity** [ericdc1/Dapper.SimpleCRUD#216]
Model:
public class Group
    {
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
    }

Controller:
connection.Insert(group);

I tested the GetList<T> methods, it works. Then I try the insert
I set Id is not duplicated or empty, 
I'm using Mac OS, .NET core 2.2 for console apps.

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
   at Dapper.SimpleCRUD.Insert[TKey,TEntity](IDbConnection connection, TEntity entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in C:\Users\Eric\Documents\GitHub\Dapper.SimpleCRUD\Dapper.SimpleCRUD\SimpleCRUD.cs:line 387
   at Selenium.GroupService.CreateSampleData(Group group) in /Users/macbookpro/RiderProjects/Selenium/Selenium/Group.cs:line 35
   at Selenium.Program.Main(String[] args) in /Users/macbookpro/RiderProjects/Selenium/Selenium/Program.cs:line 24

**Comment by game-libgdx-unity** [comment]
```
    public class Group
    {
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
    }

    public class GroupService
    {
        private readonly MySqlConnection connection;

        public GroupService()
        {
            connection = new MySqlConnection(Data.ConnectionString);
            SetDialect(Dialect.MySQL);
        }
        
        public IEnumerable<Group> GetGroup()
        {
            var result = connection.GetList<Group>();
            return result;
        }

        public void CreateSampleData(Group group)
        {
            connection.Insert(group);
        }
        
        static void Main(string[] args)
        {
            var group = new GroupService();
            var first = group.GetGroup().First();
            Console.WriteLine(first.Id);
            Console.WriteLine(first.Name);
            group.CreateSampleData(new Group
            {
                Id = "an ID",
                Name = "generated"
            });
        }
    }
```

The exception is thrown at group.CreateSampleData()

**Comment by coderabsolute** [comment]
`public string Id { get; set; }`

The `Id` should be Int?

**Comment by game-libgdx-unity** [comment]
the id column in MySQL is nvarchar(255), the Id can be a number of string.
Is this possible?

**Comment by ericdc1** [comment]
From the documentation -

[Key] -By default the Id integer field is considered the primary key and is excluded from insert. The [Key] attribute lets you specify any Int or Guid as the primary key.
