### ISSUE TITLE
encounter problem when use under VS Studio 2019

### ISSUE THREAD

**Issue by ericwonglc** [ericdc1/Dapper.SimpleCRUD#238]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.Runtime.Serialization.SerializationException: Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in Assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.

Server stack trace: 
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.SerializeMessageParts(ArrayList argsToSerialize)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage..ctor(IMethodReturnMessage mrm)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.SmuggleIfPossible(IMessage msg)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at EnvDTE._DTE.get_ActiveSolutionProjects()
   at Microsoft.VisualStudio.TextTemplating21672A6E90B91A761C1782EB5F09910E6E43B2968E42C7FDA65BC0BF0AFE1F06B0F82C78C624375F0406B7138FA27021EE4A72C240DC16E50E12BDBBA3AAA80E.GeneratedTextTransformation.GetCurrentProject()
   at Microsoft.VisualStudio.TextTemplating21672A6E90B91A761C1782EB5F09910E6E43B2968E42C7FDA65BC0BF0AFE1F06B0F82C78C624375F0406B7138FA27021EE4A72C240DC16E50E12BDBBA3AAA80E.GeneratedTextTransformation.GetConnectionString(String& connectionStringName, String& providerName)
   at Microsoft.VisualStudio.TextTemplating21672A6E90B91A761C1782EB5F09910E6E43B2968E42C7FDA65BC0BF0AFE1F06B0F82C78C624375F0406B7138FA27021EE4A72C240DC16E50E12BDBBA3AAA80E.GeneratedTextTransformation.InitConnectionString()
   at Microsoft.VisualStudio.TextTemplating21672A6E90B91A761C1782EB5F09910E6E43B2968E42C7FDA65BC0BF0AFE1F06B0F82C78C624375F0406B7138FA27021EE4A72C240DC16E50E12BDBBA3AAA80E.GeneratedTextTransformation.LoadTables()
   at Microsoft.VisualStudio.TextTemplating21672A6E90B91A761C1782EB5F09910E6E43B2968E42C7FDA65BC0BF0AFE1F06B0F82C78C624375F0406B7138FA27021EE4A72C240DC16E50E12BDBBA3AAA80E.GeneratedTextTransformation.TransformText()	LBO.Data	D:\DotNetProjects\LegalBO_Blazor\LBO.Data\LBOClassTemplate.tt	1

**Comment by ccrookston** [comment]
I am having this exact same issue. .Net Core 3.1. Google has been of no help. Any solutions?!?

**Comment by ericdc1** [comment]
I can't seem to repro this on a clean install of VS2019 and .Net Core 3.1
