### ISSUE TITLE
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.

### ISSUE THREAD

**Issue by ccrookston** [ericdc1/Dapper.SimpleCRUD#242]
```
using (var connection = OpenConnection(connString))
{
     Provider provider1 = connection.Query<Provider>("select * from Provider where ProviderId = 10001").FirstOrDefault(); // Dapper. Works.
     Provider provider2 = connection.Get<Provider>(10001); // Dapper.SimpleCrud. Fails.
}
```

I have been using Dapper.SimpleCrud for many years, and I love it. But I am just now trying to use it in a brand new project, and I'm running into a strange thing.

Visual Studio 2019
.NET Core 3.1

The first line above, with `provider` calls Dapper directly. It works fine. 
But the second line calls Dapper.SimpleCrud. And it fails. Below is the entire stack trace:

Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1051
   at Dapper.SqlMapper.<QueryImpl>d__140`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1079
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 721
   at Dapper.SimpleCRUD.GetList[T](IDbConnection connection, Object whereConditions, IDbTransaction transaction, Nullable`1 commandTimeout)
   at Dapper.SimpleCRUD.GetList[T](IDbConnection connection)
   at Dapper.SimpleRepository.Repository.GetAll[T]()
   at Dapper.SimpleRepository.Repository`1.GetAll()
   at MySolution.ConsoleApp.Program.Main(String[] args) in C:\Users\casey\source\repos\MySolution\MySolution.Console\Program.cs:line 22

  This exception was originally thrown at this call stack:
    [External Code]
    MySolution.ConsoleApp.Program.Main(string[]) in Program.cs

**Comment by ccrookston** [comment]
Well, I figured out the problem. It had to do with my models and some of the auto-generated attributes:

```
    [Table("Provider")]
    public partial class Provider
    {
        [Key]
        public int ProviderId { get; set; }

        public int ProviderTypeEnum { get; set; }

        [StringLength(100)]
        public string ProviderTypeOther { get; set; }

        [Required]
        [StringLength(100)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(100)]
        public string LastName { get; set; }

        [StringLength(200)]
        public string Email { get; set; }

        [StringLength(10)]
        public string PhoneWork { get; set; }

        [StringLength(10)]
        public string PhoneCell { get; set; }

        public bool SpecialEdPurchasing { get; set; }

        public int CreatedBy { get; set; }

        //[Column(TypeName = "datetime")]
        public DateTime Created { get; set; }

        public int? LastUpdatedBy { get; set; }

        //[Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
    }
```

The issue was this:

    [Column(TypeName = "datetime")]

Once I commented those out, it worked.  

Now I just need to go figure out how to not make that attribute generate when the models are auto-generated.

**Comment by ErikEJ** [comment]
The stack trace and the repro code does not match

**Comment by ErikEJ** [comment]
It looks like some checks are missing here: https://github.com/ericdc1/Dapper.SimpleCRUD/blob/58fffc5b1eddcbf523ab033c46e9a594f662218a/Dapper.SimpleCRUD/SimpleCRUD.cs#L1034

**Comment by ccrookston** [comment]
> The stack trace and the repro code does not match

In what way do they not match?

**Comment by ErikEJ** [comment]
Get vs GetAll ...

**Comment by ccrookston** [comment]
ah. I may have pasted an older version of the stack trace. Same error. Same model. Same root cause. I changed GetAll to Get just so it was matching what I did with the Dapper (direct) command, and then I think I must have forgotten to grab the updated stack trace.  But either way, good catch. I can update it later tonight.

**Comment by ccrookston** [comment]
To fix this bug, the following change is needed:

In `SimpleCRUD.cs`, line 1032, change:

`if (columnattr != null)`

to:

`if (columnattr != null && columnattr.Name != null)`

**Comment by ericdc1** [comment]
If you'd like to submit a PR with a test case around this I'd be glad to review and include this.
