### ISSUE TITLE
Why not add oracle samples, other database is a little cake

### ISSUE THREAD

**Issue by Marksion08** [ericdc1/Dapper.SimpleCRUD#85]
As so many office side copy everywhere, most of database are similar but oracle and DB2, it contains tablespace, table prefix, transactions, locks, functions, return values, parameter formatting, and so on.

I was trying in the place, hope to see something new here, thanks a lot!

**Comment by ericdc1** [comment]
Thanks for the feedback. I personally don't use Oracle so this isn't something I would be interested in writing. If you have some ideas and want to submit a pull request I would consider it.

**Comment by jaguarxii** [comment]
I am testing some ORMs for a project, and yours came across.

Since the project involves Informix databases, I am not able to get the simplest list from a table with three fields (integer, varchar, date).

Is there something I can do to get SimpleCRUD working against informix database?

Best regards
--
Douglas

2018-02-18 19:59:12.0559 | Fatal | http://localhost/home/GetMasters | home | GetMasters | 34 | System.Data.OleDb.OleDbException (0x80004005): [IDS/UNIX64] A syntax error has occurred.
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForMultpleResults(tagDBPARAMS dbParams, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OleDb.OleDbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\projects\dapper\Dapper\SqlMapper.cs:line 1053
   at Dapper.SqlMapper.<QueryImpl>d__136`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1081
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723
   at Dapper.SimpleCRUD.GetList[T](IDbConnection connection, Object whereConditions, IDbTransaction transaction, Nullable`1 commandTimeout) in C:\Users\ecoffman\Documents\GitHub\Dapper.SimpleCRUD\Dapper.SimpleCRUD\SimpleCRUD.cs:line 177
   at Dapper.SimpleCRUD.GetList[T](IDbConnection connection) in C:\Users\ecoffman\Documents\GitHub\Dapper.SimpleCRUD\Dapper.SimpleCRUD\SimpleCRUD.cs:line 228
   at ASPNetTestDapper.Controllers.HomeController.GetMasters() in C:\Douglas\Personal\Indigo\Pruebas\ASPNetTestDapper\ASPNetTestDapper\Controllers\HomeController.cs:line 26      [IDS/UNIX64] A syntax error has occurred.
