### ISSUE TITLE
Specified cast is not valid exception when the model does not have identity 

### ISSUE THREAD

**Issue by suresh105** [ericdc1/Dapper.SimpleCRUD#86]
Model:

 public class ClubcardV2
    {
        [Key]
        [Required]
        public long ClubcardID { get; set; }
        public long CustomerID { get; set; }
        public byte? ClubcardType { get; set; }
        public byte? ClubcardStatus { get; set; }
    }

Insert:

 public int? Insert(object entityToInsert, IDbTransaction transaction = null, int? commandTimeout = default(int?)) 
        {
            using (IDbConnection cnn = new SqlConnection(_connectionString))
            {
                return cnn.Insert(entityToInsert, transaction, commandTimeout);
            }
        }
Stack Trace:
   at Dapper.SimpleCRUD.Insert[TKey](IDbConnection connection, Object entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in C:\Users\Eric\Documents\GitHub\Dapper.SimpleCRUD\Dapper.SimpleCRUD\SimpleCRUD.cs:line 376
   at Dapper.SimpleCRUD.Insert(IDbConnection connection, Object entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in C:\Users\Eric\Documents\GitHub\Dapper.SimpleCRUD\Dapper.SimpleCRUD\SimpleCRUD.cs:line 299
   at Tesco.Com.SVS.Utils.SQLServerMapperExtensions.Insert(Object entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in D:\Final\NGC\Services\NGCDataSetup\Tesco.Com.SVS.Utils\SQLServerMapperExtensions.cs:line 57
   at NGCDataSetup.Data.Group.ClubcardV2Store.Create(IEnumerable`1 Entities) in D:\Final\NGC\Services\NGCDataSetup\NGCDataSetup.Data\Group\ClubcardV2Store.cs:line 23
   at NGCDataSetupAPI.Controllers.EntityController`4.Create(IEnumerable`1 entityList) in D:\Final\NGC\Services\NGCDataSetup\NGCDataSetupAPI\Controllers\EntityController.cs:line 37

When performing insert the statement fails with the above mentioned exception details. but the record getting inserted. Could somebody help me with this issue.

**Comment by ericdc1** [comment]
It looks like something in the get identity SQL. Have you set the database dialect to match the SQL platform you are using?
